import Navebar from '@/components/navebar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Photo_Album',
  description: 'Generated by CODE CRAFT UNIQUE',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <body className={inter.className}>
        <Navebar />
        <div className='flex'>
          <div className='w-1/4'>
            <Sidebar />
          </div>
          <div className='w-full'>
            {children}
          </div>

        </div>
      </body>
    </html>
  )
}
